### ISSUE TITLE
GPU architecture error when compling on windows

### ISSUE THREAD

**Issue by samcao416** [graphdeco-inria/nerfshop#13]
I'm using a 4090 GPU and windows 11.
When compling the cmake file in windows terminal after entering `cmake --build build --config RelWithDebInfo -j`, there comes an error, calling
`nvcc fatal   : Unsupported gpu architecture 'compute_89'`

However, I could successfully compile and build instant-ngp on my computer, before and after the failure building nerfshop.

**Comment by Snosixtyboo** [comment]
Hi,

thanks, that's an interesting error. Iirc, tinycudnn for InstantNGP does automatic detection of the latest possible compute capability for your GPU, which would be 89 for a 4090. But apparently, your installed CUDA toolkit is older and doesn't recognize this capability yet. Instant-NGP code has changed since we forked from it, getting nerfshop to behave the same might be rather tough. If it's possible, a potential fix would be to try and install the latest CUDA toolkit?

**Comment by samcao416** [comment]
Thanks for your timely reply. 

Yeah, I am using cuda 11.7.1. Previously, instant NGP didn't support the lastest CUDA. For stability, I only used CUDA 11.7.1. I will try the latest 12.1 and back to you soon.

**Comment by samcao416** [comment]
After alternating to cuda 12.1, the compilation completed successfully. Thanks a lot!
