### ISSUE TITLE
Why do we need NeRF distillation?

### ISSUE THREAD

**Issue by SCUTykLin** [graphdeco-inria/nerfshop#19]
I don't understand what motivated NeRF distillation, can you explain?

**Comment by Snosixtyboo** [comment]
I hope so. When you make edits in NeRFshop, you can only really view them inside NeRFshop because they are enabled by several auxiliary data structures. The basic InstantNGP hashgrid format is more established and is getting extensions by Nvidia (such as VR) and other researchers. When you distill, you can save and then load the result in programs that support the standard InstantNGP format. So we think of it as exporting, e.g., your Photoshop project to a .PNG, allowing many more existing solutions to interact with it. Does that make sense?

**Comment by SCUTykLin** [comment]
I understand. Thanks very much.
